# Generated by Django 3.2.9 on 2022-08-11 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Manufacturing_date', models.DateField(default=datetime.datetime(2022, 8, 11, 9, 29, 2, 793519))),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('price', models.IntegerField()),
                ('units', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brands')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.type_products')),
            ],
        ),
    ]
